# Generated by Django 5.1.15 on 2026-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='helix_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
